// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.CCCFall2017.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc692.CCCFall2017.MyGlobal;
import org.usfirst.frc692.CCCFall2017.Robot;

/**
 *
 */
public class DriveModeToggle extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveModeToggle() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(MyGlobal.isDriveModePressed == false) {
    		MyGlobal.isDriveModePressed = true;
    		switch(MyGlobal.driveModeSelected) {
	    		case arcade:
	    			MyGlobal.driveModeSelected = MyGlobal.DriveModes.mecanum;
	    			SmartDashboard.putString(MyGlobal.MODE_TYPE_DISPLAY, MyGlobal.mecanumTypeSelected.toString());
	    			break;
	    			
	    		case mecanum:
	    			MyGlobal.driveModeSelected = MyGlobal.DriveModes.tank;
	    			SmartDashboard.putString(MyGlobal.MODE_TYPE_DISPLAY, MyGlobal.tankTypeSelected.toString());
	    			break;
	    			
	    		case tank:
	    			MyGlobal.driveModeSelected = MyGlobal.DriveModes.arcade;
	    			SmartDashboard.putString(MyGlobal.MODE_TYPE_DISPLAY, MyGlobal.arcadeTypeSelected.toString());
	    			break;
    		}
    		SmartDashboard.putString(MyGlobal.DRIVE_MODE_DISPLAY, MyGlobal.driveModeSelected.toString());
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
